/** Declaration file generated by dts-gen */

export = ltijs;

declare const ltijs: {
    Provider: {
        appRoute: any;
        appUrl: any;
        close: any;
        deletePlatform: any;
        deletePlatformById: any;
        deploy: any;
        dynRegRoute: any;
        getAllPlatforms: any;
        getPlatform: any;
        getPlatformById: any;
        keysetRoute: any;
        keysetUrl: any;
        loginRoute: any;
        loginUrl: any;
        onConnect: any;
        onDeepLinking: any;
        onDynamicRegistration: any;
        onInactivePlatform: any;
        onInvalidToken: any;
        onSessionTimeout: any;
        onUnregisteredPlatform: any;
        redirect: any;
        registerPlatform: any;
        setup: any;
        updatePlatformById: any;
        whitelist: any;
    };
};

